backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Categorías", name: "categories", widget: "list", summary: "{{fields.category}}", field: { label: "Categoría", name: "category", widget: "select", options: ["Work the Floor", "Choose the wine", "Tell you what really matters"] } }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen de Portada", name: "thumbnail", widget: "image" }
      - { label: "Cuerpo del Mensaje", name: "body", widget: "markdown" }